# prompting for input

- hosts: web1
  vars_prompt:
    - name: "sitename"
      prompt: "What is new site name?"

  tasks:
    - debug: msg="The name is {{ sitename }}"

# including files

  tasks:
    - include: govapp.yml
      vars:
        sitename: Great App
    - include: loadbalancer.yml
    - include_vars: variables.yml

# grab output of task for another task
  tasks:
    - shell: /usr/bin/whoami
      register: username
    - file: path=/home/myfile.txt
            owner={{ username }} 

# add debug to tasks
  tasks:
    - debug: msg"This host is {{ inventory_hostname }} during execution"
    - shell: /usr/bin/whoami
      register: username
    - debug: var=usernamei

# handlers

  tasks:
    - copy: src=files/httpd.conf
            dest=/etc/httpd/conf
      notify:
        - Apache Restart

  handlers:
    - name: Apache Restart
      service: name=httpd state=restarted

# conditional execution

  tasks:
    - yum: name=httpd state=present
      when: asnible_os_family == "RedHat"

    - apt: name=apache2 state=present
      when: asnible_os_family == "Debian"

# another way of conditional

  tasks:
    - command: ls /path/doesnt/exist
      register: result
      ignore_errors: yes

    - debug: msg="Failure!"
      when: result|failed

# templates

  tasks:
    - template:
        src=templates/httpd.j2
        dest=/etc/httpd/conf/httpd.conf
        owner=httpd