---
# - name: test
#   hosts: webservers
#   gather_facts: no
#   tags:
#     - test
#   become: yes
#   vars_prompt:
#     - name: "sitename"
#       prompt: "What is new site name?"
#   tasks:
#   - debug: msg="The name is {{ sitename }}"

- name: Get Apache
  hosts: webservers
  become: yes
  # roles:
    # - test
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/
    max_clients: 5

  vars_prompt:
    - name: username
      prompt: What is your name?
  
  tasks:
  - name: Install Apache ensure
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html
  
  handlers:
      - name: Restart Apache
        service: name=httpd state=restarted 

- name: Start DB
  hosts: dbservers
  become: yes

  tasks: 
  
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=present
    when: ansible_os_family == "RedHat"

  - name: Start MySQL
    service: name=mysqld state=started

- name: Disable iptables
  hosts: webservers:dbservers
  become: yes

  tasks:
  - name: Stop IPTABLES NOW!!!
    service: name=iptables state=stopped