---
- hosts: webservers:dbservers
  become: yes
  gather_facts: no
  # roles:
  # - server-common

- include: webserver.yml
- include: dbserver.yml

- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Stop IPTABLES NOW!!!
    service: name=iptables state=stopped
