---
- hosts: webservers
  become: yes
  gather_facts: no
  # vars_prompt:
  #   - name: get_name
  #     prompt: What is your name?
  roles:
    - { role: webserver, username: Tadeo}
  tasks:
  - name: Stop IPTABLES NOW!!!
    service: name=iptables state=stopped