---
- name: Build an image with the command module
  hosts: vagrant
  become: yes
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=site dest=/tmp

    - name: build the image
      command: docker build -t built-by-ansible:ex2 /tmp/site

    - name: run the site in a docker container
      docker_container:
        name: test_site
        image: "built-by-ansible:ex3"
        state: started
        published_ports: all
